export {
  PAGE_TYPE_REGISTRY,
  ALL_TEMPLATE_TYPES,
  REGISTRY_VERSION,
  getPageType,
  getAllowedChildTypes,
  getMetadataGroups,
  calculateCompleteness,
  validateForPublication,
  validateForDraft,
  getGuidedSections,
  getPublicationReadiness,
  getFieldsByRequirement,
  getSectionsByRequirement,
  getDisplayProfile,
  getDisplayIdPrefix,
  getPageTypesByDisplayProfile,
  METADATA_GROUP_LABELS,
  PAGE_TYPE_CATEGORIES,
  DISPLAY_PROFILE_LABELS,
} from "./registry";

export type {
  TemplateType,
  MetadataGroupKey,
  MetadataFieldDef,
  PageTypeSection,
  PageTypeDefinition,
  PageTypeCategory,
  DisplayProfile,
  TemplateVariant,
  FieldRequirement,
  PublicationRules,
  PublicationRule,
  ValidationError,
  ValidationWarning,
  ValidationResult,
} from "./registry";
